-- Configuración de Hyprland
-- @author Neoterux
hl.config({ autogenerated = false })
-- ###################################
-- ## Carga de Variables de Entorno ##
-- ###################################
require('hyprland-neo/env').setup()

-- ################################
-- ## Configuracion de Monitores ##
-- ################################
require('hyprland-neo/monitors').setup()

-- #########################
-- ## Look & Feel ##
-- #########################
require('hyprland-neo/lookandfeel').setup()

-- ###############
-- ## Autostart ##
-- ###############
require('hyprland-neo/autostart').setup()

-- ##################
-- ## Keybindings  ##
-- ##################
require('hyprland-neo/binds').setup()

-- ###############################
-- ## Ventanas y Workspaces     ##
-- ###############################
require('hyprland-neo/workspaces').setup()
